### ISSUE TITLE
Ошибка: [pdoTools] The "tplPath" and "elementsPath" parameters are deprecated and will be removed in the next version.

### ISSUE THREAD

**Issue by des-yogi** [sergant210/pdoTools#317]
Версии: 
php — 7.3, 
Modx — 2.8.3, 
pdoTools 2.13.2 (последняя на данный момент).

При вызове pdoPage (ajax=scroll) вылазит ошибка: `[pdoTools] The "tplPath" and "elementsPath" parameters are deprecated and will be removed in the next version.`
Если не использовать этот режим, ошибки нет...

**Comment by sergant210** [comment]
Так и запланировано. Это предупреждение о том, что в следующей версии эти параметры сниппетов будут удалены.
