### ISSUE TITLE
Modx3 RC1 

### ISSUE THREAD

**Issue by eydolan** [sergant210/pdoTools#323]
## Сообщение об ошибке / Error message
no error in log

### Резюме / Summary
pdoMenu cant display differnt parents

Краткое резюме о чем эта проблема. / A short summary of what this problem is about.
in modx 3 RC1 if I put
[[pdoMenu?
    &parents=`0`
]]
it displays fine
but if I choosse a specific resource with chidren I just get a blank page in froont end and no error message
eg
[[pdoMenu?
    &parents=`1`
]]
not working

### Шаг для воспроизведения / Step to play

Как воспроизвести проблему, включая пользовательский код, если это необходимо. / How to reproduce the problem, including custom code if needed

### Наблюдаемое поведение / Observed behavior

Как она себя вела после следующих шагов выше. / How she behaved after the next steps above.

### Ожидаемое поведение / Expected behavior

Как это должно вести себя после следующих шагов выше. / How it should behave after following the steps above.

### Environment

php 8.0.1 
3.0.0-rc1

Версия miniShop2, версия MODX, Apache/Nginx и версия, версия mysql, браузер и т.д. Любая соответствующая информация. / MiniShop2 version, MODX version, Apache / Nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by bYemma** [comment]
I have a similar problem with MODX 3.0.0-rc1 and pdoTools v3.0.0-beta. When you choose another `parents` value than `0` the result contains a bunch of resources which are not the right ones.

**Comment by bYemma** [comment]
The `parents` parameter is transformed to an array while it should be still a string. This causes the problems here I think...
```[17-Jan-2022 18:20:24 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /var/www/xyz/htdocs/core/components/pdotools/src/Fetch.php:749```

In the pdoMenu snippet on line 73 somehow `$scriptProperties['parents']` changes to an array:
https://github.com/modx-pro/pdoTools/blob/3a358ecee89963c8718fd6537f0ad44dec87bfe6/core/components/pdotools/elements/snippets/snippet.pdomenu.php#L73
Right before line 73 `$scriptProperties['parents']` is a string, after the line it is an array.

Before: `string(1) "3"`
After: `array(1) { [0]=> string(1) "3" }`

Why? I don't know... In my opinion the exploded value should never be assigned to `$scriptProperties['parents']`?

**Comment by sergant210** [comment]
Fixed in MODX 3.0.1.
