### ISSUE TITLE
Неправильная работа сниппета pdoNeighbors в pdoTools 3

### ISSUE THREAD

**Issue by h-futuris** [sergant210/pdoTools#327]
### Сообщение об ошибке / Error message

Сниппет **pdoNeighbors** в **pdoTools 3** выводит ссылки сразу на все предыдущие и все последующие посты относительно текущего. В то время как должен выводить по одной ссылке (предыдущий пост слева, последующий - справа).

### Environment
MODX - 3.0.0-rc1, pdoTools 3, Apache 2.4.6-97, MySql 10.4.22, PHP 7.3.33.

**Comment by sergant210** [comment]
Fixed.
