### ISSUE TITLE
Can't load pdoTools classes — MODX 3

### ISSUE THREAD

**Issue by SnowCreative** [sergant210/pdoTools#328]
## Сообщение об ошибке / Error message
[2022-01-30 12:32:01] (ERROR @ [PATH TO CORE]/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 666) Could not load class: pdoFetch from pdofetch

### Резюме / Summary

Installed 3.0.0-beta in my MODX 3.0.0-rc1 installation

### Наблюдаемое поведение / Observed behavior
The error above appears in the log, and web pages do not load at all, just a white screen. I assume other pdoTools classes won't lead either, but pages stop loading after the first error so I can't tell what would happen beyond where this code appears.

Is this still the way to use pdoFetch? 

```
$pdo = $modx->getService('pdoFetch');
$menus = $pdo->getCollection('modResource', array(
	'published' => true,
	'hidemenu' => false,
	'deleted' => false,
	'parent' => '0'
), array(
	'includeTVs' => 'menuposition',
	'sortby' => 'menuindex'
));
```

### Environment

MODX 3.0.0-rc1.   pdoTools 3.0.0-beta

**Comment by sergant210** [comment]
MODX 3 uses a [dependency injection container](https://docs.modx.com/3.x/en/extending-modx/di-container). modX::getService is marked as deprecated.
`$pdo = $modx->services->get('pdotools');`

**Comment by jmacdonald-spectacle** [comment]
This solution isn't working for me. MODX 3.0.1; pdoTools: 3.0.0

Code:
```
$pdo = $modx->services->get('pdotools');
$page = $pdo->getArray('modResource',['id' => 1]);
```
Error:
```
PHP message: PHP Fatal error: Uncaught Error: Call to undefined method ModxPro\PdoTools\CoreTools::getArray() 
```
Am I missing something?

**Comment by SnowCreative** [comment]
For 3.0, if you're using "modResource", then you also have to have this at the top of your code:

use MODX\Revolution\modResource;

And, in answer to my own question above, I had to change the first line to:

$modx->services->get(Fetch::class);

and I also had to put this at the top of my code:

use ModxPro\PdoTools\Fetch;

Maybe you need to use pdoPage instead of just "pdotools"?

**Comment by jmacdonald-spectacle** [comment]
Thanks @SnowCreative. I was following an old post that got me using pdoFetch, but you're right, pdoPage is probably more update-proof.

Thanks again!

**Comment by SnowCreative** [comment]
pdoFetch works fine. I use it instead of pdoPage. For example, to load just one page as in your post:


```
use MODX\Revolution\modResource;
use ModxPro\PdoTools\Fetch;

$pdo = $modx->services->get(Fetch::class);
$docs = $pdo->getCollection('modResource', array(
    'id' => 1
), array(
    'includeTVs' => 'tvname'
));

if(!empty($docs)) {
    foreach ($docs as $doc) {
        // your code here 
        echo $doc['pagetitle'];
        echo $doc['tvname']
    }
}

```

**Comment by jmacdonald-spectacle** [comment]
That's cool too. thx!

**Comment by SnowCreative** [comment]
You can do this for individual resources:
```
use MODX\Revolution\modResource;
use ModxPro\PdoTools\Fetch;

$pdo = $modx->services->get(Fetch::class);
$doc = $pdo->getArray('modResource', ['id' => 1]);

if(!empty($doc)) {
  // your code here 
  echo $doc['pagetitle'];
  // etc.
}

```

or, to include TVs:
```
$doc = $pdo->getArray('modResource', ['id' => 1],['includeTVs' => 'tvname,tvname2']);
```

**Comment by jmacdonald-spectacle** [comment]
Hey @SnowCreative. I wanted to keep a single code branch for modx2/pdo2 and modx3/pdo3, so I came up with the following. I had to use a couple of snippets, but it works fine.

Just thought I'd share.

a) In the main snippet, change `$pdo = $modx->getService('pdoFetch');` to `$pdo = $modx->runSnippet('pdoFetch');`

b) pdoFetch snippet:
```
$versionData = $modx->getVersionData();
$version = (int) $versionData['version'];
  
if ( $version == 2 ) {
  return $modx->getService('pdoFetch');
} else {
  return $modx->runSnippet('pdoFetch3');
}
```

b) pdoFetch3 snippet:
```
use MODX\Revolution\modResource;
use ModxPro\PdoTools\Fetch;

return $modx->services->get(Fetch::class);
```
-John

**Comment by sergant210** [comment]
@jmacdonald-spectacle This is because the pdoTools service does not have this method.
Try this
```
$pdo = $modx->services->get('pdofetch');
$page = $pdo->getArray('modResource',['id' => 1]);
```

**Comment by jmacdonald-spectacle** [comment]
Oh that's better. Thanks @sergant210 .

If I update my snippet, I get:
```
$versionData = $modx->getVersionData();
$version = (int) $versionData['version'];
  
if ( $version == 2 ) {
  return $modx->getService('pdoFetch');
} else {
  return $modx->services->get('pdofetch');
}
```

**Comment by SnowCreative** [comment]
> $pdo = $modx->services->get('pdofetch');
> $page = $pdo->getArray('modResource',['id' => 1]);

OK, so the weird change here is that "f" has to be lowercase for MODX3. Using upper case "F" makes it fail.

So can we say that pdoTools as a whole is working fine now with MODX3? Are any issues outstanding?

**Comment by sergant210** [comment]
> $modx->services->get(Fetch::class);

I would not advise doing this if you need to get a service. Doing this you will get a new object of the Fetch class, not the initialized service.

> OK, so the weird change here is that "f" has to be lowercase for MODX3. Using upper case "F" makes it fail.

In the next version I'll add aliases for "pdoFetch" and "pdoTools".

**Comment by sergant210** [comment]
> Are any issues outstanding?

I hope so.
