### ISSUE TITLE
[MODX3] pdotools_fenom_parser + tv.image приводят к Fatal error:  Allowed memory size

### ISSUE THREAD

**Issue by wanderer20** [sergant210/pdoTools#329]
## Сообщение об ошибке / Error message
Так таковой ошибки от модуля не наблюдается, просто где-то думаю цикл бесконечный, который привел к таким последствиям:

```
[17-Feb-2022 18:07:32 Europe/Moscow] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /var/www/.../core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOQuery.php on line 686
[17-Feb-2022 18:07:32 Europe/Moscow] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /var/www/.../core/src/Revolution/modX.php on line 2454
[17-Feb-2022 18:07:32 Europe/Moscow] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
```

### Резюме / Summary

> Краткое резюме о чем эта проблема. / A short summary of what this problem is about.

Проблема возникает при открытии детальной страницы элемента, если в любое поле tv с типом image добавить изображение.  

### Шаг для воспроизведения / Step to play

> Как воспроизвести проблему, включая пользовательский код, если это необходимо. / How to reproduce the problem, including custom code if needed

**1.** Создать шаблон с именем **item**
**2.** Создать **tv**, с типом - **изображение**, поставить доступно в шаблоне **item**
**3.** Скачать и установить **pdoTools 3.0.0-beta**, внести настройки:
```
pdotools_fenom_modx - да
pdotools_fenom_parser - да // при включении этой настройки - происходит ошибка, на страницу с материалом не попасть
pdotools_fenom_php - да
```
**4.** Создать документ, присвоить ему шаблон **item** и **добавить в поле с изображением какую-либо картинку**
**5.** Попытаться перейти на этот документ в браузере - получить 500 или 502

### Наблюдаемое поведение / Observed behavior

> Как она себя вела после следующих шагов выше. / How she behaved after the next steps above.

На своем железе выдает **502** ошибку, на тестовом сайте modhost.pro - **500** ошибку

### Ожидаемое поведение / Expected behavior

> Как это должно вести себя после следующих шагов выше. / How it should behave after following the steps above.

Должна открываться детальная страница элемента, без ошибок и утечек памяти

### Environment

> Версия miniShop2, версия MODX, Apache/Nginx и версия, версия mysql, браузер и т.д. Любая соответствующая информация. / MiniShop2 version, MODX version, Apache / Nginx and version, mysql version, browser, etc. Any relevant information.

- modx 3.0.0-rc2
- pdoTools 3.0.0-beta
- php 7.4

**Comment by sergant210** [comment]
![image](https://user-images.githubusercontent.com/4679725/154798636-f2aa0b5b-65b0-4b67-a510-00c04d342406.png)
MODX 3.0.0-rc2

Системные настройки
![image](https://user-images.githubusercontent.com/4679725/154798842-ca3269b8-fd8f-416d-8ddb-1de75cf948ed.png)

Картинка на месте.
![image](https://user-images.githubusercontent.com/4679725/154798747-27f5543a-cb2c-431a-8e1d-a1bd5b51b6b3.png)

Не могу получить указанную ошибку.

**Comment by wanderer20** [comment]
@sergant210 хм, настройки верные, что вы показали, попробовал сейчас повторить проблему на тесте - снова ее получил. Ниже привел скриншоты, могу выслать доступ до панели теста, где есть проблема

![Screenshot_115](https://user-images.githubusercontent.com/8947500/154799719-061b0df3-503d-4b44-baf7-63a847e5a055.png)

Тип поля - стандартный - image
![Screenshot_116](https://user-images.githubusercontent.com/8947500/154799739-79a4d750-b5b1-4d97-abd7-b351ab9157a9.png)

Применяем например к стандартному шаблону:
![Screenshot_117](https://user-images.githubusercontent.com/8947500/154799756-f7b2c53b-13b4-4ec6-a402-ca743b9b9a25.png)

Переходим на домашнюю страницу с шаблоном BaseTemplate
![Screenshot_119](https://user-images.githubusercontent.com/8947500/154799780-6d4c4067-c4c6-40b8-8685-df2c69eabff8.png)

Загружаем картинку
![Screenshot_120](https://user-images.githubusercontent.com/8947500/154799787-ca00651f-e4c6-4cb0-81da-dc8bde94755a.png)

И в браузере переходим на главную страницу
![Screenshot_121](https://user-images.githubusercontent.com/8947500/154799801-af19014b-c8fb-49bc-bf31-ecf035b351e3.png)

**Comment by wanderer20** [comment]
@sergant210 парень из соседней ветки https://github.com/modx-pro/pdoTools/issues/328 пишет о похожем, что не может загрузиться страница

**Comment by sergant210** [comment]
Установил параметр ввода в "изображение" и получил ошибку (было только для вывода)
```
[2022-02-19 15:06:37] (ERROR @ Unknown0) PHP warning: Unknown: Cannot call session save handler in a recursive manner
```
Буду разбираться.

**Comment by shipulina** [comment]
¯\_(ツ)_/¯
/core/src/Revolution/Sources/modMediaSource.php  ~1400


```php
<?php 
/**
    * Parse any tags in the properties
    *
    * @param array $properties
    *
    * @return array
*/
public function parseProperties(array $properties)
{
    if (empty($properties)) {
        $properties = $this->getProperties();
    }       
    // $this->xpdo->getParser();
    // if ($this->xpdo->parser) {
    //     foreach ($properties as &$property) {
    //         $this->xpdo->parser->processElementTags('', $property['value'], true, true);
    //     }
    // }

    return $properties;
}
```

**Comment by Mu7ic** [comment]
Аналогичной проблемой натолкнулся на modx 3.0.1-pl

**Comment by MaticSulc** [comment]
> ¯_(ツ)_/¯ /core/src/Revolution/Sources/modMediaSource.php ~1400
> 
> ```
> <?php 
> /**
>     * Parse any tags in the properties
>     *
>     * @param array $properties
>     *
>     * @return array
> */
> public function parseProperties(array $properties)
> {
>     if (empty($properties)) {
>         $properties = $this->getProperties();
>     }       
>     // $this->xpdo->getParser();
>     // if ($this->xpdo->parser) {
>     //     foreach ($properties as &$property) {
>     //         $this->xpdo->parser->processElementTags('', $property['value'], true, true);
>     //     }
>     // }
> 
>     return $properties;
> }
> ```

This fixed the issue in my case, although I am not certain that it doesn't cause any other issues.

**Comment by sergant210** [comment]
Fixed.
