### ISSUE TITLE
pdotools: не срабатывают некоторые переменные и плейсхолдеры fenom синтаксиса в чанках

### ISSUE THREAD

**Issue by jonimant** [sergant210/pdoTools#331]
## Сообщение об ошибке / Error message

Сообщений об ошибках не наблюдается.

### Резюме / Summary

Отображаются пустые поля, которые были введены в контактной форме на сайте. 

### Шаг для воспроизведения / Step to play

Вызывается Formit из шаблона инструкцией {include 'contact_form'}

Чанк 'contact_form':
```
{'!FormIt' | snippet : [
    'hooks'=>'email,FormItSaveForm',
    'emailTpl'=>'tpl.contact_form',
    'emailTo'=> 'email@mailbox.com' ,
    'emailFrom'=> $_modx->config.emailsender,
    'emailSubject'=> 'Сообщение с сайта ' ~ $_modx->config.site_url,
    'validate'=> 'name:required,email:required,message:required',
    'validationErrorMessage'=>'Укажите корректную информацию. Заполните все необходимые поля.',
    'successMessage'=>'Спасибо, сообщение отправлено!.',
    'errTpl'=>'[[+error]]' 
]}
```

Чанк: 'tpl.contact_form':
```
<p>Name: {$name}</p>
<p>Email: {$email}</p>
<p><strong>Question</strong></p>
<p>{$message | nl2br}</p>
```

### Наблюдаемое поведение / Observed behavior

Приходит письмо c пустыми полями следующего вида:
Subject: 
Name:
Email: 
Message:

При этом в FormItSaveForm все данные сохраняются, которые были введены пользователем в контактной форме на сайте.

Работает если другие параметры, например:
Если указать в чанке 'tpl.contact_form' 
```
<p>Name: [[+name]]</p>
<p>Email: [[+email]]</p>
<p>Email: [[+message:nl2br]]</p>
```
А вчанке contact_form изменить строчку 
```
&emailSubject'=> 'Сообщение с сайта ' ~ $_modx->config.site_url,
&emailSubject => 'Сообщение с сайта ' ~ $_modx->config['site_url']',
```

### Ожидаемое поведение / Expected behavior

Сообщение с сайта / 
Name: Anton
Email: test@mail.com
Message: bla bla bla

### Environment

Опции : 
Разрешить Modx в Fenom: Да
Использовать Fenom на страницах: Да
Использовать Fenom и в чанках: Да
Использовать PHP в Fenom: Да

Версия modx 3.0.0-pl (ночная сборка)
Pdotools: 3.0.0-beta
Babel: 3.1.0-pl
PHP: 7.4

**Comment by sergant210** [comment]
Эта ошибка должна быть в и MODX 2.х версии. Но никто видимо не пользуется феномом в письмах FormIt.

**Comment by sergant210** [comment]
Исправлено.
