### ISSUE TITLE
MODX3: Cannot access protected property ModxPro\\PdoTools\\Fetc in pdoResources, line 57

### ISSUE THREAD

**Issue by patrickatwsrn** [sergant210/pdoTools#334]
### Резюме / Summary

I'm playing around with modx3 and pdoTools. The installation was flawless, but I have a encountered a problem with proResources.

Simple pdoResources call causes Error 500

### Шаг для воспроизведения / Step to play

Example code inside a modx template:
```
[[!pdoResources?
    &parents=`[[*id]]`
    &tpl=`static-nav_tpl`
    &tplWrapper=`static-nav_tplWrapper`
    &limit=`999`
    &templates=`5`
    &sortby=`{"menuindex":"asc"}`
    &includeContent=`1`
    &depth=`0`
]]
```
### Наблюдаемое поведение / Observed behavior

Error 500 and this logfile:
```
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Cannot access protected property ModxPro\\PdoTools\\Fetch::$config in /var/www/vhosts/example.com/httpdocs/web/core/cache/includes/elements/modx/revolution/modsnippet/19.include.cache.php:57\nStack trace:\n

#0 /var/www/vhosts/example.com/httpdocs/web/core/src/Revolution/modScript.php(88): include()\n

#1 /var/www/vhosts/example.com/httpdocs/web/core/src/Revolution/modX.php(1923): MODX\\Revolution\\modScript->process()\n

#2 /var/www/vhosts/example.com/httpdocs/web/core/cache/includes/elements/modx/revolution/modsnippet/29.include.cache.php(20): MODX\\Revolution\\modX->runSnippet()\n

#3 /var/www/vhosts/example.com/httpdocs/web/core/src/Revolution/modScript.php(88): include('...')\n

#4 /var/www/vhosts/example.com/httpdocs/web/core/src/Revolution/modParser.php(505): MODX\\Revolution\\modScript->process()\n

#5 /var/www/vhosts/example.com/httpdocs/web/core/components/pdotools/src/Parsing/Parser.php(273): MODX\\Revolution\\modParser->processTag()\n

#6 /var/www/vhosts/mod...', referer: https://example.com/
```
### Ожидаемое поведение / Expected behavior

pdoResources should return a list of things retrieved by the snippet.

### Environment

This is the code mentioned in the error log above:
https://github.com/modx-pro/pdoTools/blob/3a358ecee89963c8718fd6537f0ad44dec87bfe6/core/components/pdotools/elements/snippets/snippet.pdoresources.php#L58
```
Source pdoResources (19)
55    if (!empty($tplWrapper) && (!empty($wrapIfEmpty) || !empty($output))) {
56        $output = $pdoFetch->getChunk($tplWrapper, array_merge($additionalPlaceholders, ['output' => $output]),
57            $pdoFetch->config['fastMode']); // 
58    }
```
MODX 3.0.0pl
pdoTools 3.0.0beta
php 8.1.4

**Comment by patrickatwsrn** [comment]
I don't get the meaning behind this, but if I remove tplWrapper from the pdoResources call, I suddenly get a response.

I have also verified this problem on another server with differnt tpl chunks. The result is the same Error 500.

**Comment by patrickatwsrn** [comment]
Sidenote: Adding &fastMode to the pdoresources call (0 or 1) has not noticable effect.

**Comment by patrickatwsrn** [comment]
# Possible solution to the problem (PR below)

If we use 

> $pdoFetch->getConfig['fastMode']

instead of 

> $pdoFetch->config['fastMode'] 

it solves the problem

```
        $output = $pdoFetch->getChunk(
            $tplWrapper, 
            array_merge( $additionalPlaceholders,['output' => $output] ),
            $pdoFetch->getConfig['fastMode']
        );
```

Note: This is also a "solution" (see comment below)

```
        $output = $pdoFetch->getChunk(
            $tplWrapper, 
            array_merge( $additionalPlaceholders,['output' => $output] ),
            $pdoFetch->config('fastMode')
        );
```

This is used multiple times in pdoUsers.

Which one is the right solution?

**Comment by patrickatwsrn** [comment]
After digging through the code I've found out, that fastMode is retrieved in two different ways:

IMPORTANT: The code referenced below is not identical to the code downloaded via package manager (3.0.0.beta).

## pdoResources

https://github.com/modx-pro/pdoTools/blob/3a358ecee89963c8718fd6537f0ad44dec87bfe6/core/components/pdotools/elements/snippets/snippet.pdoresources.php#L58

> $pdoFetch->config['fastMode']

## pdoUsers

https://github.com/modx-pro/pdoTools/blob/04d63ab22dc34a85ee684fc6f0062bedde5cf890/core/components/pdotools/elements/snippets/snippet.pdousers.php#L171

> $pdoFetch->config['fastMode']

## pdoArchive

https://github.com/modx-pro/pdoTools/blob/04d63ab22dc34a85ee684fc6f0062bedde5cf890/core/components/pdotools/elements/snippets/snippet.pdoarchive.php#L111

https://github.com/modx-pro/pdoTools/blob/04d63ab22dc34a85ee684fc6f0062bedde5cf890/core/components/pdotools/elements/snippets/snippet.pdoarchive.php#L122

https://github.com/modx-pro/pdoTools/blob/04d63ab22dc34a85ee684fc6f0062bedde5cf890/core/components/pdotools/elements/snippets/snippet.pdoarchive.php#L131

https://github.com/modx-pro/pdoTools/blob/04d63ab22dc34a85ee684fc6f0062bedde5cf890/core/components/pdotools/elements/snippets/snippet.pdoarchive.php#L141

> $pdoFetch->config('fastMode')

The later syntax doesn't seem to make a problem.

That makes me wonder if my "fix" is not a solution, but rather less buggy.

**Comment by patrickatwsrn** [comment]
Question: What is the right branch for Version 3.0.0beta?

**Comment by sergant210** [comment]
```
$pdoFetch->getConfig['fastMode']
```
This is the wrong decision. You are specifying a non-existent array. You can specify any other array. For example
```
$pdoFetch->blabla['fastMode']
``` 
The result will be the same. You will receive either a notice or a warning (depending on PHP version)/

**Comment by sergant210** [comment]
Fixed.
