### ISSUE TITLE
$this should be $modx

### ISSUE THREAD

**Issue by Esger** [sergant210/pdoTools#338]
https://github.com/modx-pro/pdoTools/blob/3a358ecee89963c8718fd6537f0ad44dec87bfe6/assets/components/pdotools/connector.php#L8

Error in console:
jquery-3.5.1.min.js:2 POST https://c0xxx.paas1.ams.modxcloud.com/assets/components/pdotools/connector.php 500

Php error: 
PHP Fatal error: Uncaught Error: Using $this when not in object context in 
/www/assets/components/pdotools/connector.php:8 Stack trace: #0 {main} thrown in /www/assets/components/pdotools/connector.php on line 8

**Comment by sergant210** [comment]
Fixed.
