### ISSUE TITLE
The "tplPath" and "elementsPath" parameters are deprecated in 2.13.2-pl

### ISSUE THREAD

**Issue by dimasites** [sergant210/pdoTools#339]
Установлен pdoTools 2.13.2-pl
ControlErrorLog засыпан ошибками:
`[pdoTools] The "tplPath" and "elementsPath" parameters are deprecated and will be removed in the next version.
`

Я использую эту настройку абсолютно на всех проектах, указав её один раз в сис. настройке ++pdotools_elements_path (со значением «{assets_path}chunks/» для удобной организации папок в проекте. 

**Вопрос:** Хочу уточнить, в следующей версии планируется её выпилить совсем или просто запретить возможность переопределять при вызове сниппета (в коде шаблона например), но глобальную сис. настройку оставить?

**В этой связи стоит обратить внимание**, что некоторые дополнения, которые интегрированы с pdoTools используют его настройку, например: https://github.com/Sterc/imagecropper#parameters

**Предлагаю** лучше эту настройку не убирать совсем, а именно, в целях безопасности (видел где-то коммент Сергея Шлокова, но не смог сейчас найти) запретить её установку при вызове сниппета. (т.к. технически сниппет можен и контент-менеджер вызвать)

**Comment by dimasites** [comment]
Кажется, при выводе сообщения нет проверки, включен вообще вывод ++log_deprecated.

И плюс к этому, если из системных настроек удаление не планируется, предлагаю ошибку отправлять в лог только если именно в переданных параметрах она была указана, а не глобально.

**Comment by sergant210** [comment]
Ты перепутал. Разговор идет о параметрах сниппетов, а не о системной настройке. И в лог сообщение пишется именно когда у сниппета указан любой из этих параметров.
В следующей версии будет добавлена системная настройка, позволяющая  разрешать использовать эти параметры. Т.е. если админ сайта разрешил, то контент-менеджеры могут указывать любые пути. Если запретил, то менеджеры должны использовать только файловые элементы из указанной в системной настройке папки.

**Comment by dimasites** [comment]
Ок, большое спасибо за пояснение!

Подозреваю, что по умолчанию будет выключена настройка, и это повысит безопасность. Выглядит как хорошее решение!

Проверю свои сниппеты. может в наборы параметров дефолтное значение указано... А по поводу сторонних дополнений, раз возможность полностью не удаляется, вопрос тоже снят.
