### ISSUE TITLE
MODX 3.0.1 bug

### ISSUE THREAD

**Issue by MaticSulc** [sergant210/pdoTools#344]
## Сообщение об ошибке / Error message

`Uncaught TypeError: ModxPro\\PdoTools\\CoreTools::debugParserMethod(): Argument #3 ($properties) must be of type array, string given.`

### Резюме / Summary

After updating to MODX 3.0.1-pl, using makeUrl functions with smarty (fenom) syntax throws an error.

Как воспроизвести проблему, включая пользовательский код, если это необходимо. / How to reproduce the problem, including custom code if needed

`<link href="{$_modx->makeUrl($_modx->config.site_start)}assets/theme/css/styles.min.css" rel="stylesheet" />`

### Наблюдаемое поведение / Observed behavior
Error 500

### Ожидаемое поведение / Expected behavior
Printing the link normally.

### Environment

MODX 3.0.1-pl

**Comment by MaticSulc** [comment]
After testing, #322 fixes this issue.

**Comment by sergant210** [comment]
Fixed
