### ISSUE TITLE
Проблема обработки parents=0

### ISSUE THREAD

**Issue by Alexij2** [sergant210/pdoTools#350]
## Сообщение об ошибке / Error message
Небольшая неприятность.
Если указать parents = 0 и depth = 0, то pdoResources выводит все ресурсы **включая вложенные**.
Если указать parents = '0,'  То работает как надо.
Если Parents больше нуля, то все работает корректно.

Версия PdoTools 2.13.2-pl, MODX 2.8.4

**Comment by sergant210** [comment]
Есть простое решение - прочитать [документацию](https://docs.modx.pro/komponentyi/pdotools/obshhie-parametryi).

**Comment by Alexij2** [comment]
Ааа. семен семеныч... это фитча ). Но в моем случае я хотел через pdoResource вывести только 1й уровень, как в pdoMenu.
Прошу прощения за бессмысленную исушку.

**Comment by Alexij2** [comment]
Хотя нет... речь идет именно о том что parents = 0 и depth = 0. те логично что parents = 0 - не ограничена выборка, но depth =0 не работает получается. А вот если указать например каталог id = 2, то да, depth = 0 срабатывает. Об этом речь.

**Comment by sergant210** [comment]
Алексей, я как и ты не знаю какую Василий закладывал логику. Чтобы узнать, нужно копать код. Открываем, смотрим - если parent пустой (а ноль это тоже пусто), то depth не учитывается. Мне кажется, ты мог бы это сделать и без меня.

П.С. Кстати, это логично. Если ты хочешь вывести всё без ограничений, то зачем тебе уровень? А если нужен уровень, то укажи точку отсчёта.

**Comment by Alexij2** [comment]
Сергей, логика и так понятна, что depth не учитывается. Видимо, эта особенность только меня задела.
Ладно, значит так и должно быть.
